func/init.cpp: add missing InitVfList
This fixes the linker error for `t.advection`:

in function `Advection<MeshCartesian<double, 3ul> >::Init(Suspender::Sem&)':
func/init_u.h:145: undefined reference to `void InitVfList`